[package]
name = "rdeps"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.4.7"
inquire = "0.6.2"
walkdir = "2.4.0"
